# Conservative model configuration

# Spread / totals thresholds
spread_threshold: 3
spread_weight: 1.0        # lower weighting than aggressive
low_total: 38             # require even lower totals to trigger under
high_total: 68            # require even higher totals to trigger over
total_weight: 1.0

# Situational adjustments
injury_qb: 2              # QB injury
injury_other: 1
trap_game: 2
travel_penalty: 1
matchup_adv: 2
explosiveness: 2
weather_penalty: 2
cold_weather: 2
home_field: 2
