# Aggressive model configuration

# Spread / totals thresholds
spread_threshold: 3       # trigger if spread is at least 3 points
spread_weight: 2.0        # aggressive weighting on spread edges
low_total: 40             # totals below this trigger an "under" lean
high_total: 65            # totals above this trigger an "over" lean
total_weight: 2.0

# Situational adjustments
injury_qb: 4              # QB injury impact
injury_other: 2           # other injuries
trap_game: 4              # trap game penalty
travel_penalty: 2         # cross-country eastward travel
matchup_adv: 3            # matchup advantages
explosiveness: 3          # explosiveness adjustment
weather_penalty: 3        # bad weather adjustment
cold_weather: 3           # southern teams in <40°F northern games
home_field: 3             # home field advantage
